name: Upload and Notify

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: Linux
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.timestamp }}
    steps:
      - id: step1
        run: echo "timestamp=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT
  build:
    needs: job1
    runs-on: Linux
    steps:
      - name: Test with environment variables
        run: echo $FILE_NAME
        env:
          FILE_NAME: GitHubContext-${{needs.job1.outputs.output1}}.json
      - name: Configure the CLI
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          pwd
          ls -lrt
          whoami
          echo "$GITHUB_CONTEXT" > githubcontext
      - name: Test the CLI
        run: |
          aws sts get-caller-identity
          aws s3 ls
