name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ICROSERVICE_NAME: "ozone-relay"
      HAS_DEV: "true"
      GITHUB_HEAD_REF: ${{ GITHUB_HEAD_REF }}
      GITHUB_REF: ${{ GITHUB_REF }}
      GITHUB_BASE_REF: ${{GITHUB_BASE_REF  }}
    steps:
      - uses: actions/checkout@v2
      - name: Run on pull request
        if: ${{ github.event_name == 'pull_request' }} 
        run: |
          echo "This is because of PULL REQUEST"
          echo $ICROSERVICE_NAME
          echo $HAS_DEV

      - name: Run on push
        if: ${{ github.event_name == 'push' }} 
        run: |
          echo "This is because of PUSH"
          echo "GITHUB_HEAD_REF = $GITHUB_HEAD_REF"
          echo "GITHUB_REF = $GITHUB_REF"
          echo "GITHUB_BASE_REF = $GITHUB_BASE_REF"
