name: CI

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      name:
        default: "Octocat"
        description: "Name to greet"
env:
  name: Farhan

jobs:
  build:
    runs-on: bash
    outputs:
      output1: ${{ steps.step1.outputs.name }}
    steps:
      - id: step1
#       - name: Decide variable
        run: |
          if [[ ${{ github.event_name }} -eq 'push' ]]; then
          echo "name=$name" >> $GITHUB_OUTPUT
          else
          echo "name=${{ github.event.inputs.name }}" >> $GITHUB_OUTPUT
          fi
  deploy:
    runs-on: bash
    steps:
      - name: Run always
        run: echo "Hello ${{needs.build.outputs.output1}}"
