name: CI

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      name:
        default: "Octocat"
        description: "Name to greet"
env:
  name: Farhan

jobs:
  build:
    runs-on: bash
    steps:
      - name: Decide variable
        run: |
          if [[ ${{ github.event_name }} -eq 'push' ]]; then
          name=$name
          else
          name=${{ github.event.inputs.name }}
          fi
      - name: Run on push
        if: ${{ github.event_name == 'push' }} 
        run: |
          echo "This is because of PUSH"
          echo $ICROSERVICE_NAME
          echo $HAS_DEV
          bash print.sh
      - name: Run always
        run: echo "Hello $name"
