name: CI

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      name:
        default: "Octocat"
        description: "Name to greet"
env:
  name: Farhan

jobs:
  build:
    runs-on: bash
    outputs:
      output1: ${{ steps.step1.outputs.name }}
    steps:
      - id: step1
      - name: Decide variable
        run: |
          if [[ ${{ github.event_name }} -eq 'push' ]]; then
          echo "name=$name" >> $GITHUB_OUTPUT
          else
          echo "name=${{ github.event.inputs.name }}" >> $GITHUB_OUTPUT
          fi
      - name: Run on push
        if: ${{ github.event_name == 'push' }} 
        run: |
          echo "This is because of PUSH"
          echo $ICROSERVICE_NAME
          echo $HAS_DEV
          bash print.sh
      - name: Run always
        run: echo "Hello ${{needs.build.outputs.output1}}"
