name: Upload to S3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: bash
    steps:
      - id: step1
        run: |
          pwd
          ls -lrt
          whoami
          aws --version
      - uses: actions/checkout@master
      - name: Upload S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: "farhnm-ttn"
          source_dir: "/home/ubuntu/actions-runner/upload"
#           destination_dir: "code/cost_report.zip"
