name: Upload to S3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: bash
    steps:
      - name: Configure the CLI
        run: |
          pwd
          ls -lrt
          whoami
          touch /tmp/testfile.text
          aws --version
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}}
          export AWS_DEFAULT_REGION=us-east-1
      - name: Test the CLI
        run: |
          aws sts get-caller-identity
          aws s3 ls
          aws s3 cp /tmp/testfile.text s3://farhnm-ttn
          
