name: Upload to S3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: bash
    steps:
      - id: step1
        run: |
          pwd
          ls -lrt
          whoami
          aws --version
      - name: Upload S3
        uses: shallwefootball/upload-s3-action@v1.2.0
        id: S3
        with:
          aws_bucket: "farhnm-ttn"
          source_dir: "/home/ubuntu/actions-runner/nohup.out"
#           destination_dir: "code/cost_report.zip"
